### ISSUE TITLE
Collecting on/off

### ISSUE THREAD

**Issue by NotUsed** [cool7su/Broken_Clashbot#28]
would like to see an option to disable collecting in village
check if collect is on/off
on =>collect
off =>skip(ignore)

**Comment by msh2050** [comment]
http://gamebot.org/showthread.php?tid=675 you can implement it from this they add this feature
but there  but is not stable as clashbot

**Comment by NotUsed** [comment]
I found the other bot more stable and "finished" feelind but I like dead/active base attack mode in this
