### ISSUE TITLE
Lower full army count

### ISSUE THREAD

**Issue by codebroken** [cool7su/Broken_Clashbot#3]
Currently offers ability to fight at 70, 80, 90, 100% camp full.  Allow lower army size necessary.

**Comment by cool7su** [comment]
working on this. Enable 10%~100% selection

**Comment by cool7su** [comment]
This is will be very good combine with nuke storage. 20% TH sniper & DE nuke

**Comment by cool7su** [comment]
added & committed to patch-source-1. Waiting for test.
