### ISSUE TITLE
Auto update

### ISSUE THREAD

**Issue by ckodex** [cool7su/Broken_Clashbot#34]
So many people use this version but fail to check github.  Couldn't we add a feature that checks version number on github and then automatically downloads new source code if available?

**Comment by NotUsed** [comment]
well maybe not auto upload but notifications, new version is avaiable

**Comment by cool7su** [comment]
Then we will need a place to let bot pull the version information. Simple create another file in master branch will do. Like direct link to readme.md
https://raw.githubusercontent.com/cool7su/Broken_Clashbot/master/README.md

**Comment by NotUsed** [comment]
good idea

**Comment by codebroken** [comment]
Very cool, and shouldn't take much time to implement at all.  I'll make this high priority.
