### ISSUE TITLE
Broken is back? 

### ISSUE THREAD

**Issue by cmestres** [cool7su/Broken_Clashbot#36]
Broken, why did u get demoted?!?!

**Comment by cmestres** [comment]
I strongly suggest you to get in the gamebot.org community. They r grouping many devs.. They r more friendly.. They r the true clashbot creators. Scar_face008 and others are there!

**Comment by cool7su** [comment]
I think he is back with us. I know gamebot, but I feel current version of clashbot is more advanced, especially broken's version. Lots of work has been done, if we switch, it will need lots of effort.

This become some kind forum now. LOL

**Comment by codebroken** [comment]
Didn't realize I had been demoted.  I told them I didn't have time to be active. Exactly why I have zero desire to join gamebot.  

I'm perfectly happy with an opensource model and think its the best way to go. It doesn't work unless everyone contributes but it can be damn good if it they do.  All members of the community are necessary to make this the best it can be.  I'll write and fix issues when I can. Everyone else can help by adding code, helping to document bugs, and making feature requests.

**Comment by mk89pwnz** [comment]
completely agree with u ;) gamebot are making secured dll so calshbot won't steal source code, so dunno is it open sorcen anymore to. And this is atm the most advanced version of them all that is open source and this github section is even better then a forum, everyone cad report bug give pull request and so on. Atm bot is perfect to my with monitoring script. I noticed some bug i will post them later,

**Comment by NotUsed** [comment]
Well clashbot management treating its forum users like trash, not sure why broken joined 'team' in first place and why would people stay there. Nice to see him back.

**Comment by jimbob007** [comment]
Just wanted to say thanks broken and cool7su! I hate the direction they've taken the bot now, and the way they've deleted all the awesome mods you guys have made. Its a real shame they are going after money now.

**Comment by ckodex** [comment]
lmao, just tried to login to clashbot for first time in a long time...I've been banned!

**Comment by codebroken** [comment]
Made a better place for simple discussions.  Didn't want to setup a whole forum where people have to register, just a simple chatroom: http://www.e-chat.co/room/77641
