### ISSUE TITLE
DE priority

### ISSUE THREAD

**Issue by cmestres** [cool7su/Broken_Clashbot#37]
Just an idea.. DE priority..

Everytime we have X lightning spells, attack bases with mininum DE set. It should check every rotation.. Giving priority to DE zap before attacking bases with mininum gold/elixir

**Comment by mk89pwnz** [comment]
DE zapping is close to perfect. Only one feature I would like to have is that attack algorithm would after DE zap search for TH to snipe and if possible attack it will like 20 troops this way we wouldn't loose trophy

**Comment by NotUsed** [comment]
no sure why it should be priority, I use barch, Im fresh th9, never used lightning, I keep upgrading both heroes same time and Im stuck 200k de

**Comment by cmestres** [comment]
Fresh TH7 is hard to farm DE. This could be implemented as a checkbox. A lot of ppl take to long to upgrade the king on TH7.. And, without priority, lightnings stays too much time idle.

**Comment by xtcian** [comment]
True... but then again... why waste 60k+ elixer on lightning if barch gonna
steal all the dark anyways? Hitting de before or after fight is 2
completely diff fighting algorithms... at least I think so... I myself
prefer to hit only afterwards so I can save elixer..... because sometimes
my barch get it all anyways :)

**Comment by mk89pwnz** [comment]
Why not zap? 2h and I get minimum 1k DE :D if i boost it's 4k... when i need fast DE it's epic even when u are TH9. Never tried to attack live base, maybe will try to abuse TH8 when I get my lvl6 giants :)

**Comment by cool7su** [comment]
Tick zap with full army only will give priority to normal raid with troops. Clear the flag will give priority to nuke, whenever spell ready bot will search and nuke. I think this is already covered.

**Comment by codebroken** [comment]
Agreed, gonna close this because if you do as cool7su suggests then once you have full spell factory but not full army it will search for base to zap (completely ignoring bases based on other requirements).
