### ISSUE TITLE
Enhasment:- Experiance mod during waiting for full attack/add to statistic

### ISSUE THREAD

**Issue by msh2050** [cool7su/Broken_Clashbot#44]
I think it is better to let the experience mode work with normal farming so we can farm and get more experience.and we can just make it work if the camp 50% or less (so the farm attack will not be late)
and  also it is god to add this to the statistics..

* please inform if the enhancement request/ suggestion should be in the chat room (I think if must be recorded for following)

**Comment by shariqriaz** [comment]
also add the option to go on exp mod when gold/elexir full..its simple code i added it myself on ur version v 1

**Comment by msh2050** [comment]
thanks a lot. I will test now
