### ISSUE TITLE
Jordan DDOS brokenbot.org

### ISSUE THREAD

**Issue by cmestres** [cool7su/Broken_Clashbot#53]
Jordan registered in the site as GORDON .. Few time later site is DOWN! This happened after a user called drtailz made a topic calling ppl to brokenbot.org

**Comment by maxcom99** [comment]
you get cloudfare and you get cloudfare... sigh

**Comment by maxcom99** [comment]
Jordan Rash is the clashbot dude?

**Comment by maxcom99** [comment]
cloudfare for all...

**Comment by xtcian** [comment]
Easy to defend... goto site logs... track ip... block ip... 

If you wanna attack back.... oh oh soooo many ways... none illegal. ... and oohhh revenge can be soooo sweet.... just make sure you have proof... like what ip attacked you...

**Comment by maxcom99** [comment]
bro there was 1.1mil IPs .. someone paid to have a botnet of compromised WordPress servers send it.
